supabase/gotrue-dart

lib/src/gotrue_api.dart

Fixes https://github.com/supabase/gotrue/issues/90
Missed the URL encoding of the http parameter. Thanks @icecream78 for helping out 😁

fix: URL encode redirectTo

---

lib/src/auth_options.dart

Added comments within AuthOptions to clarify what `redirectTo` and `scopes` do. 
There were no comments within AuthOptions.
There are comments to explain what `redirectTo` and `scopes` do.

Added comments within AuthOptions to better understand AuthOptions

---

.gitignore
lib/src/gotrue_api.dart
lib/src/gotrue_client.dart
lib/src/session.dart
pubspec.yaml
test/client_test.dart
test/subscriptions_test.dart

Fixes #34 
There is currently no way to set the current session from a jwt. (For instance, passed to a backend function)
A setAuth() method has been introduced which mirrors the one from the js client. Intoduced in [this PR](https://github.com/supabase/gotrue-js/pull/83).

setAuth() method for setting the session with a provided jwt

---

lib/src/provider.dart

Add new auth providers, following the [October Beta 2021](https://github.com/supabase/supabase/releases/tag/0.21.10) announcement:
> [...] new Auth providers this month: Slack, Spotify 
Furthermore, add `twitch` provider. 
There is a feeling that they just forgot to add it last time in the Supabase client on Dart 🤔
No issue. While developing my Flutter application, I found that there is no provider data in the `Provider` enum 😉 
No.
No.

Add `slack`, `spotify` and `twitch` Auth providers

---

lib/gotrue.dart
lib/src/gotrue_api.dart
lib/src/gotrue_client.dart

Bug fix
You cannot define `GotrueError` or `GoTrueClient` as type, because it's not exported. In addition, it was not possible to specify custom [CookieOptions](https://github.com/supabase/gotrue-dart/blob/main/lib/src/gotrue_client.dart#L33) because the class wasn't exported too.
Files are now properly exported.
In addition, I removed unnecessary imports. 
I noticed some types begin with `GoTrue` and some with `Gotrue`. Wouldn't it be better if the beginning would be equal?
Examples:
- `GoTrueClient`
- `GoTrueApi`
vs
- `GotrueError`
- `GotrueResponse`
- `GotrueSession`

fix: export missing types

---

CHANGELOG.md
lib/src/gotrue_client.dart
lib/src/version.dart
pubspec.yaml

> @osaxma I found out that the error only occurs when I recover auth session. In other words, subscribing after login directly doesn't have an issue, but subscribing after a session recovery has the issue.
> The issue is that onAuthStateChange does not trigger an event after a session recovery, which is used to update the accessToken for the realtime client in here:
https://github.com/supabase-community/supabase-dart/blob/2d5be1c6968da5944f8b3b039e351b38a953d815/lib/src/supabase.dart#L169-L180
If gotrue-dart emits a signedIn or tokenRefreshed event after session recovery, this issue would be fixed.
https://github.com/supabase-community/realtime-dart/issues/35#issuecomment-1024998157

fix: missing event on session recover

---

lib/src/gotrue_error.dart

When printing `response.error`, it'll print for example:
```
GotrueError(message: Database error querying schema)
```
Instead of:
```
Instance of 'GotrueError'
```

add `toString` method to `GotrueError`class

---

lib/src/gotrue_api.dart
lib/src/gotrue_client.dart

Closes https://github.com/supabase-community/gotrue-dart/issues/52
Summary:
add the `JWT` as an `Authorization` header when refreshing tokens.

add jwt to headers when refreshing token

---

lib/src/auth_options.dart
lib/src/gotrue_api.dart
lib/src/gotrue_client.dart
test/client_test.dart

So far it wasn't possible to set `userMetadata` on sign up. A second request was necessary. If only one request comes through, it could cause problems. 
I saw in `gotrue-js` [that it's possible](https://github.com/supabase/gotrue-js/blob/12d02c35209bbd9f8f51af8d0aeee5e86fcc2a6e/src/GoTrueApi.ts#L91) and tested it with the supabse cli local.
In addition, I put the comments from `AuthOptions` to the correct position, because it wasn't shown in VS Code on the parameters.

feat: set user metadata on sign up

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

Publish new version of gotrue-dart to be used inside of supabase-dart

chore: publish version 0.1.6

---

pubspec.yaml

It seems like the pub.dev started detecting potential leaks of secrets. The leak detection detected the following line from `infra/docker-compose.yml` as leak of secret, and in order to publish a package, I had to add false_secrets to `pubspek.yml` file. 
```yml
GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID: 53566906701-bmhc1ndue7hild39575gkpimhs06b7ds.apps.googleusercontent.com
```
https://dart.dev/tools/pub/pubspec#false_secrets

feat: add false_secrets to pubspec to be able to bypass leak detection

---

lib/src/fetch.dart
lib/src/gotrue_api.dart
lib/src/gotrue_client.dart
lib/src/gotrue_response.dart
test/client_test.dart
test/custom_http_client.dart

Same reason as https://github.com/supabase-community/postgrest-dart/pull/66
When writing the test, I realized that the response doesn't include the status code. I think that's a nice to have. When trying to implement the status code I realized that e.g. `GotrueUserResponse` does extend `GotrueResponse`, but parameter like `rawData` aren't copied to the new instance. When adding the status code to `GotrueResponse` you would have to repeatedly pass it to the new instance. So I created helper constructors to create a new instance from the general `GotrueResponse`. So `rawData` and `statusCode` are copied too.
In addition, I made them all `final`.

feat: custom http client and statuscode in response

---

CHANGELOG.md
lib/src/fetch.dart
lib/src/gotrue_api.dart
lib/src/gotrue_client.dart
lib/src/gotrue_error.dart
pubspec.yaml

Currently when accessToken refresh fails for any reason, gotrue-dart never retries to update access token and the user is signed out. This PR fixes that by retrying to refresh the token if it fails due to network error. 
It will also not sign a user out just because a token refresh failed. Instead, it will retry every 5 seconds to get a new token. 
Related https://github.com/supabase-community/supabase-flutter/issues/33

fix: Retry access token refresh when offline

---

CHANGELOG.md
lib/src/open_id_connect_credentials.dart

Dependent on 
https://github.com/supabase/gotrue/pull/430

Make nonce optional

---

lib/src/constants.dart
lib/src/gotrue_client.dart

This PR is a rework of https://github.com/supabase-community/gotrue-dart/pull/71 pretty much. 
Instead of just retrying token refresh every 5 seconds, this PR will use a `Completer` to return a valid `GoTrueSessionResponse` upon successful token refresh after retry.

fix: use completer in the retry logic to return value when token refresh is complete

---

lib/src/gotrue_api.dart

Currently, when there is an error with phone auth sign up, type cast error is thrown. This PR fixes that bug and the developers will be able to see the actual error. 
Fixes https://github.com/supabase-community/supabase-flutter/issues/132

fix: type casting of phone auth response

---

lib/src/user_attributes.dart

https://github.com/supabase-community/supabase-dart/issues/121#issue-1296626049

able to update phone number with auth.update method

---

lib/gotrue.dart
lib/src/constants.dart
lib/src/gotrue_api.dart
pubspec.yaml
test/client_test.dart

Added generateLink method reffer to the [supabase's Auth(Server only) API
](
https://supabase.com/docs/reference/javascript/auth-api-generatelink#generate-invite-link)

Add generateLink method

---

example/main.dart
lib/src/gotrue_api.dart
lib/src/gotrue_client.dart
lib/src/gotrue_response.dart
test/client_test.dart
test/provider_test.dart

fixes https://github.com/supabase-community/supabase-flutter/issues/182
See my [comment](https://github.com/supabase-community/supabase-flutter/issues/182#issuecomment-1212398301) for a question regarding the sign in event and strange naming of  `data`.

fix: don't require session after signup

---

CHANGELOG.md
lib/src/fetch.dart
lib/src/version.dart
pubspec.yaml
test/client_test.dart

Right now Japanese and Korean breaks when they are in the user metadata. This PR fixes it. Haven't look into it too much , but not sure why the same happens with Postgrest or realtime, but they are fine. 
fixes https://github.com/supabase-community/supabase-flutter/issues/212

fix: encoding issue with some languages

---

lib/src/fetch.dart
lib/src/gotrue_client.dart

fix https://github.com/supabase-community/supabase-flutter/issues/244

fix: email redirect

---

lib/src/fetch.dart

Currently, `redirect_to` parameter of the `request` method is being URI encoded twice, resulting in wrong value being passed as the query parameter. This PR fixes it.
Fixes https://github.com/supabase-community/supabase-flutter/issues/244
Because redirect_to is not being passed properly, `emailRedirectTo` is not working
`emailRedirectTo` should be working with this one.

fix: properly add redirect_to when making request

---

lib/src/gotrue_client.dart

Currently, verify otp throws upon successful verification. This PR fixes that.
Fixes https://github.com/supabase-community/supabase-flutter/issues/251
Successful verify throws
Verification should go through successfully without any issues.

fix: verify otp throws on verification.

---

lib/src/gotrue_client.dart
test/client_test.dart

Currently using supabase-flutter, there is no way to detect the exception thrown to parse deep links other than the initial link using `initialSession`
```dart
try {
await SupabaseAuth.initialSession;
} catch(error) {
// handle initial error here
}
```
This PR allows the users to use `onAuthStateChange` to listen to exceptions thrown during deep link parsing like this:
```dart
supabase.auth.onAuthStateChange.listen(
(data) {
// handle auth state change here
},
onError: (error) {
// handle parsing error here.
}
);
```
Fixes https://github.com/supabase-community/supabase-flutter/issues/211

feat: fail to getSessionFromUrl throws error on onAuthStateChange

---

lib/src/types/auth_response.dart
test/auth_response_test.dart

Bug fix #100
Use reg exp to generate the snake cases
Generate the snake cases without using reg exp

fix: avoid positive lookbehind in snake case extension

---

lib/src/gotrue_client.dart
test/client_test.dart

There were some other `redirect_to` issue where the parameter was URL encoded twice. This fixes it.
Fixes https://github.com/supabase-community/supabase-flutter/issues/261

fix: redirect_to double URL encoding issue

---

lib/src/gotrue_client.dart

Bug fix
Currently, the lib uses `refreshToken` but it may be `null`. There is a check in the first line and we should use that variable. 
Use `token` (which is `refreshToken ?? currentSession?.refreshToken`) instead of `refreshToken`

Use correct token for refreshing 

---

lib/src/gotrue_admin_api.dart
lib/src/types/user_attributes.dart
test/admin_test.dart

The js function `deleteUser` returns an `UserResponse` object, but for me the api always returned an empty object. I don't know where the issue lies, so I created an issue on gotrue https://github.com/supabase/gotrue/issues/804
In addition, I changed the type of `userMetadata` and `appMetadata` to `Map`. because `List` didn't work.

feat: more admin methods

---

CHANGELOG.md
lib/src/types/user.dart
lib/src/version.dart
pubspec.yaml

In response to today's issues (https://status.supabase.com/incidents/zmw9wwlwnj8g), it might be a good idea to not require `role` to be non-nullable if the actual type is nullable.

fix: allow nullable role in User.fromJson()

---

pubspec.yaml

There was a warning when trying to release a new version, because `collection` package used in `gotrue_client.dart` is not listed on pubspec.yaml. This PR fixes it.
collection v1.17.0 used 2.12.0 as minimal Dart SDK version.

fix: add collection to pubspec.yaml

---

lib/src/gotrue_client.dart
lib/src/types/session.dart
test/provider_test.dart

In response to a recent issue supabase/supabase-flutter#342 I opened,  `session` does not contain `provider_refresh_token` despite the `authResponse` having one. 
Now, the session should contain `provider_refresh_token` (if there is).
Also, the reason `provider_token` turns `null` after Supabase refreshes token does not depend on the parsing issue, but rather that the `authResponse` no longer contains both `provider_token` and `provider_refresh_token`. Therefore, I was not able to set automatic refresh token for provider as well.

feat: add providerRefreshToken to session

---

CHANGELOG.md
lib/src/gotrue_client.dart
lib/src/version.dart
pubspec.yaml

Recreates  https://github.com/supabase/gotrue-js/pull/603
This is the endpoint we need to hit for native auth. i'm also going to be working on native auth in the supabase-flutter repo.
Here's a WIP of the PR
https://github.com/supabase/supabase-flutter/blob/signInWithIdToken/README.md#native-auth-example

Add experimental signInWithIdToken for Apple, Google

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

Fixes issue in `supabase-flutter`.
> 
> Fixes Because every version of flutter from sdk depends on meta 1.8.0 and gotrue >=1.5.0 depends on meta ^1.9.0, flutter from sdk is incompatible with gotrue >=1.5.0.
> And because every version of supabase from git depends on gotrue ^1.5.0, flutter from sdk is incompatible with supabase from git.
> So, because supabase_flutter depends on both flutter from sdk and supabase from git, version solving failed.
>

Fixes incompatible meta version

---

lib/src/gotrue_client.dart
test/client_test.dart

I'm resetting the count when we successfully set a new session. This should be the case after a call to `_callRefreshToken` with a new session, but for repeatedly calling `_saveSession` from `recoverSession` as well.
close https://github.com/supabase/supabase-flutter/issues/393

fix: properly reset refresh retry count

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

Lowers the version of `meta` to ^1.7.0, because Flutter 2.8.0 requires meta v1.7.0
Fixes https://github.com/supabase/supabase-flutter/issues/404

lower the meta version to v1.7.0

---

lib/src/constants.dart
lib/src/types/auth_response.dart
lib/src/types/user.dart

Bug fix, feature, docs update, ...
Please link any relevant issues here.
This PR adds some default values on some values.
This PR might not make sense at first glance, but the goal of this PR is to have the Flutter SDK not throw errors when the backend makes an mistake and changes the return type to nullable. Some of the values that are given default values are not very widely used. Having the app throw for parsing an object that isn't even used within the code is a pain, and this PR minimizes the effect of the mistake made on the backend. 
There probably will be a few more of these PR coming!
Fixes https://github.com/supabase/supabase-flutter/issues/414

fix: add default value to auth response

---

lib/src/gotrue_client.dart

I've noticed that the expiry margin gets wrongly applied. If `expiresAt` is minimal more than `timeNow` it still doesn't get fired.
See [gotrue-js](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L1081) implementation.

fix: correct expiry margin

---

lib/src/gotrue_client.dart

Currently, the only way to listen to exceptions thrown during `recoverSession` is to handle `SupabaseAuth.initialSession`, which I think we should move away from, since it's a weird design pattern to just have a variable just for the initial session.
This PR allows users to listen to errors emitted on `recoverSession` by adding `onError()` on `onAuthStateChanged`. So that it is easier to handle the initial auth exceptions as well as on going exceptions happening during token refresh can be all handled through `onAuthStateChanged`.

fix: use _notifyException to handle recoverSession errors

---

CHANGELOG.md
lib/src/gotrue_client.dart
lib/src/version.dart
pubspec.yaml

If  ` _notifyAllSubscribers `is called before` _saveSession`, then the `session` of the emitted `AuthState` will be `null`, because it uses `_currentSession` which is still `null` if `_saveSession` has not been called.
With #127 the session of the emitted `AuthState` is `null`.
Same as before #127 , emitted `AuthState` contains the corresponding session.

fix: prevent AuthState signedIn with null session

---

lib/src/gotrue_client.dart
test/client_test.dart
test/custom_http_client.dart

Completers are used in gotrue client to be able to retry token refresh and return the final retry result, but currently the result of `_callRefreshToken` are directly being returned. 
This PR makes `_callRefreshToken` void and makes sure that the result of the completer are returned for those that needs to refresh the session.

properly handle completer

---

lib/src/gotrue_client.dart
test/client_test.dart
test/custom_http_client.dart

Currently, `signedIn` event fires for every `passwordRecovery` event, which is not so intuitive. This PR prevents from `signedIn` event from firing for a `passwordRecovery` event.
Copied over from this js PR https://github.com/supabase/gotrue-js/pull/629/files

fix: signedIn event will not fire for passwordRecovery event
