lib/src/user_attributes.dart
When Changing password , the password is save  , then when you logout and login, it will error out...
but if you try to use your email address as your password you will be logged in..
this PR will fix that hope you  can review this thanks
=> Fix Password and other attributes defaulting to email field.

lib/gotrue.dart, lib/src/user_attributes.dart
This PR Allow us to do this
```
import 'package:gotrue/gotrue.dart' show UserAttributes;
```
so we can use the UserAttributes Class when updating Authenticated User
=> Export UserAttributes

.github/workflows/main.yml, CHANGELOG.md, lib/gotrue.dart, lib/src/cookie_options.dart, lib/src/fetch.dart, lib/src/fetch_options.dart, lib/src/gotrue_api.dart, lib/src/gotrue_client.dart, lib/src/gotrue_response.dart, lib/src/session.dart, lib/src/subscription.dart, lib/src/user.dart, lib/src/user_attributes.dart, pubspec.yaml, test/client_test.dart, test/provider_test.dart, test/subscriptions_test.dart
Migration to null safety.
Not using null-safe dart
Using null-safe dart
Used setUpAll instead of setUp to indicate when the client needed to be initialized for client_test.dart
Ready for review now
@phamhieu
=> Migrate to null safety

lib/src/gotrue_api.dart, lib/src/gotrue_client.dart
Is there a general communication channel to talk about different issues?
And what is the current developing mode for 3rd party packages? Are they test or used somewhere?
=> Fixes expiresAt conversion to int and getUser resolving JSON

lib/src/gotrue_api.dart, lib/src/gotrue_client.dart, lib/src/provider.dart, lib/src/session.dart
This matches the oauth scopes, redirectTo and provider_token of gotrue-js.
This PR needs to be merged as well, to fix breaking bugs: #13
=> Parses provider token and adds oauth scopes and redirectTo

.github/workflows/main.yml, analysis_options.yaml, lib/src/cookie_options.dart, lib/src/gotrue_response.dart
Updated Github actions to check for letters per line and lint errors. 
Related to https://github.com/supabase/supabase-dart/pull/28
Github actions does not check for letters per line and lint errors. 
Github actions does check for letters per line and lint errors.
=> Check for letters per line and lint errors in Github actions

lib/src/provider.dart
Adds support for new external OAuth providers (discord, twitter & apple)
No support for specific 0Auth providers
Supports the new 0Auth providers
N/a
=> Update External OAuth Providers

lib/src/gotrue_api.dart, lib/src/gotrue_client.dart, lib/src/user.dart, test/client_test.dart
Feature.
Fixes https://github.com/supabase/supabase-dart/issues/38
Phone authentication is added. Added the following methods:
- `signUpWithPhone`
- `signInWithPhone`
- `sendMobileOTP`
- `verifyMobileOTP`
=> Phone sign in

infra/docker-compose.yml
Attempting to fix docker-compose so that tests work again. 
tests fail to connect to docker probably because something in docker-compose is not right. 
tests will run without problem.
=> fix: docker-compose so that tests work

lib/src/constants.dart, lib/src/gotrue_client.dart, lib/src/version.dart, test/client_test.dart
Added `X-Client-Info` header for better debugging on the server side. 
Related https://github.com/supabase/supabase-dart/issues/45
=> feat: Added x-client-info to default header

.github/workflows/main.yml, example/main.dart, lib/src/cookie_options.dart, lib/src/fetch.dart, lib/src/gotrue_api.dart, lib/src/gotrue_client.dart, lib/src/gotrue_response.dart, lib/src/subscription.dart, lib/src/user.dart, test/client_test.dart, test/provider_test.dart, test/subscriptions_test.dart
The [Github action we used to use for Dart language](https://github.com/cedx/setup-dart) is now deprecated, and there is a [one published by the official dart language team](https://github.com/marketplace/actions/setup-dart-sdk), so using that one instead of the current one. 
Using a deprecated Github Action.
Using Github Action published by the official dart lang team and also testing stable, beta, dev version of dart language.
=> fix: using official dart lang github action

.gitignore, lib/src/gotrue_api.dart, lib/src/gotrue_client.dart, pubspec.yaml, test/client_test.dart, test/subscriptions_test.dart
Improves client tests:
- Adds env variables which allow a user to override GOTRUE_URL, GOTRUE_TOKEN, GOTRUE_USER_EMAIL, and GOTRUE_USER_PASS[word] (so that a dev can test locally while still allowing the CI/CD to perform tests as usual)
- Improved type checking via the TypeChecker matcher
- Improved gotrue client error output (prints the client error instead of showing `Actual: <Instance of 'GotrueError'>`)
- Fixes null check / overrride on signIn test (was causing CI to fail before)
=> Improve client tests

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
Publishing new version
version is 0.1.1
version is 0.1.2
N/A
=> chore: publish version 0.1.2

lib/src/fetch.dart, lib/src/gotrue_api.dart, lib/src/gotrue_client.dart, lib/src/gotrue_response.dart, lib/src/session.dart, lib/src/subscription.dart, test/client_test.dart
Fixes #39
Addresses PR feedback in #40
=> fix: update currentSession.user when GoTrueClient.update is called

CHANGELOG.md, lib/gotrue.dart, lib/src/constants.dart, lib/src/gotrue_client.dart, lib/src/version.dart, pubspec.yaml, test/subscriptions_test.dart
- feat: add tokenRefreshed auth event
- chore: export Subscription type
- refactor: check & return invalid session data error
=> update new auth events

.github/workflows/main.yml
Fixes the issue where github actions are not running 
Related https://github.com/dart-lang/setup-dart/issues/46#issuecomment-1040022923
=> fix: github action file to properly run tests

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
=> chore: Publish version 0.2.2

lib/src/gotrue_client.dart
This should fix https://github.com/supabase-community/supabase-flutter/issues/253
=> fix: reset token retry count on session remove

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
Should be merged after https://github.com/supabase-community/gotrue-dart/pull/96 and https://github.com/supabase-community/gotrue-dart/pull/95
=> chore: publish v1.0.2

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- fix: avoid positive lookbehind in snake case extension ([#100](https://github.com/supabase-community/gotrue-dart/pull/101))
=> chore: bump version to 1.1.0

lib/src/gotrue_admin_api.dart
Aligned to the [gotrue-js](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueAdminApi.ts#L161) implementation
=> feat: paginate listUsers

CHANGELOG.md, lib/src/types/mfa.dart, lib/src/version.dart, pubspec.yaml
close https://github.com/supabase/supabase-flutter/issues/387
Should I increase the version as well?
=> fix: make Factor.friendlyName nullable

lib/src/gotrue_client.dart
This PR introduces a feature that allows for greater customization of HTTP headers in the Supabase Dart library. but we need first to enable the customization also in the gotrue-dart
Everything is described here:
https://github.com/supabase/supabase-dart/pull/185
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
Add any other context or screenshots.
=> make headers editable

lib/src/gotrue_client.dart
close supabase/supabase-flutter#457
This is a proposal to update the headers in sync. I would listen in supabase-dart to the sync stream and update the headers.
=> feat: sync onAuthStateChange

lib/gotrue.dart, lib/src/gotrue_client.dart, test/src/gotrue_mfa_api_test.dart
exports the unexported MFA related types.
=> chore: export mfa types
